### ISSUE TITLE
data format should be valid MessagePack

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/simplerpc#3]
What we do now is a concatenation of two MessagePack buffers, which results in a buffer that is no longer valid MessagePack.
```python
data = msgpack.packb(method_name) + msgpack.packb(params)
```
I suggest we make the data format valid MessagePack:
```python
 data = msgpack.packb([method_name, params])
```

I also suggest not to force the params to be a map because for most commands a list would be simpler to parse.

**Comment by antoinealb** [comment]
I don't think concatenating two MessagePack buffers make it invalid, it is simply two different objects.

I agree for the map issue though.
